config/routes.rb
require 'sidekiq/web'
# root 'pages#home'
# skip_before_action :authenticate_user!, :only => [:index]

Rails.application.routes.draw do
  # devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  get '/ates/export', to: 'ates#export'
  resources :ates
  resources :ates_imports, only: [:new, :create]

  get '/objectivity_ate_marks/export', to: 'objectivity_ate_marks#export'
  resources :objectivity_ate_marks
  resources :objectivity_ate_marks_imports, only: [:new, :create]

  get '/objectivity_ou_marks/export', to: 'objectivity_ou_marks#export'
  resources :objectivity_ou_marks
  resources :objectivity_ou_marks_imports, only: [:new, :create]


  get '/monitoring_objectivity_ous/export', to: 'monitoring_objectivity_ous#export'
  resources :monitoring_objectivity_ous
  resources :monitoring_objectivity_ous_imports, only: [:new, :create]

  get '/monitoring_objectivity_ates/export', to: 'monitoring_objectivity_ates#export'
  resources :monitoring_objectivity_ates
  resources :monitoring_objectivity_ates_imports, only: [:new, :create]

  get '/mouos/export', to: 'mouos#export'
  resources :mouos
  resources :mouos_imports, only: [:new, :create]

  get '/ous/export', to: 'ous#export'
  resources :ous
  resources :ous_imports, only: [:new, :create]

  get '/archive2021_ous/export', to: 'archive2021_ous#export'
  resources :archive2021_ous

  get '/archive2021_ates/export', to: 'archive2021_ates#export'
  resources :archive2021_ates

  get '/archive2021_ou_marks/export', to: 'archive2021_ou_marks#export'
  resources :archive2021_ou_marks

  get '/archive2021_ate_marks/export', to: 'archive2021_ate_marks#export'
  resources :archive2021_ate_marks

  get '/recreate_logins_for_all_users', to: 'home#recreate_logins_for_all_users'
  get '/help', to: 'home#help'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/monitoring_objectivity_ates_imports', to: 'monitoring_objectivity_ates_imports#new'
  get '/monitoring_objectivity_ous_imports', to: 'monitoring_objectivity_ous_imports#new'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  # root :to => redirect("/users/sign_in")

  root :to => 'home#index'

  #
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ou.rb
class Ou < ApplicationRecord
  belongs_to :mouo
  belongs_to :ate

  has_many :monitoring_objectivity_ou

  def self.search(search)
    if search
      where('name || cast(code as varchar(5)) LIKE ?', "%#{search}%")
    end
  end

  self.per_page = 20

  # set per_page globally
  WillPaginate.per_page = 20

  def to_s
    "#{code} ..#{name[-50..-1]}"
  end

end

app/controllers/ous_controller.rb
class OusController < ApplicationController
  load_and_authorize_resource :instance_name => :item
  before_action :authenticate_user!

  def index
    @ous = Ou.accessible_by(current_ability).paginate(page: params[:page]).order('code ASC')
    if current_user.admin?
      if !params[:search].nil?
        @ous = Ou.accessible_by(current_ability).search(params[:search]).paginate(page: params[:page]).order('code ASC')
      end
    else
      if !params[:search].nil?
        @ous = Ou.accessible_by(current_ability).search(params[:search]).paginate(page: params[:page]).order('code ASC')
      end
    end
  end

  def export
    @ous = Ou.accessible_by(current_ability)
    render xlsx: 'ous_list_' + DateTime.now.getlocal.to_s.gsub(' ', '-').gsub(':', '.'), template: '/ous/export.xlsx.axlsx'
  end

  def new
    @ates = Ate.accessible_by(current_ability)
    @mouos = Mouo.accessible_by(current_ability)
    @ou = Ou.new
    if !@ou.nil?
      render :edit
    else
      flash[:success] = t("ous.errors.cant_create_new")
      redirect_to :action => 'index'
    end
  end

  def show
    @ou = Ou.accessible_by(current_ability).find(params[:id])
  end

  def create
    @ates = Ate.accessible_by(current_ability)
    @mouos = Mouo.accessible_by(current_ability)
    @ou = Ou.new(ou_params)
    if @ou.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @ates = Ate.all
    @mouos = Mouo.all
    @ou = Ou.find(params[:id])
  end

  def delete
    Ou.accessible_by(current_ability).find(params[:id]).destroy
    return
  end

  def destroy
    @ou = Ou.accessible_by(current_ability).find(params[:id])
    @ou.destroy
    respond_to do |format|
      format.html { redirect_to ous_url, notice: t("ous.notice.destroyed") }
      format.json { head :no_content }
    end
    # redirect :action => 'index'
  end

  def update
    @ou = Ou.accessible_by(current_ability).find params[:id]
    # respond_to do |format|
    if @ou.update ou_params
      flash[:success] = t("ous.notice.updated")
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end


  def ou_params
    params.require(:ou).permit(:code, :name, :ate_id, :mouo_id, :contact_fio, :contact_phone)
  end

end

app/helpers/ous_helper.rb
module OusHelper
end

app/views/ous/_edit.html.haml
%h4= t("ous.actions.edit")
= form_for @ou do |f|
  .form-group
    %table
      %tr
        %td= t("ous.code")
        %td= f.number_field :code, autofocus: false, placeholder: t("ous.code"), class: 'form-control'
      %tr
        %td= t("ous.full_name")
        %td= f.text_field :name, autofocus: false, placeholder: t("ous.name"), class: 'form-control'
      %tr
        %td= t("ous.ate_full_name")
        %td= f.collection_select :ate_id, @ates, :id, :name, prompt: true, placeholder: t('ou.choose_ate')
      %tr
        %td= t("ous.mouo_full_name")
        %td= f.collection_select :mouo_id, @mouos, :id, :name, prompt: true, placeholder: t('ou.choose_mouo')
      %tr
        %td= t("ous.contact_fio")
        %td= f.text_field :contact_fio, autofocus: false, placeholder: t("ous.contact_fio"), class: 'form-control'
      %tr
        %td= t("ous.contact_phone")
        %td= f.text_field :contact_phone, autofocus: false, placeholder: '+7-xxx-xxx-xxxx', class: 'form-control'
      %tr
        %td{:colspan=>2}
          .form-actions
            = f.submit @ou.new_record? ? t("buttons.create") : t("buttons.save"), :class => 'btn btn-primary btn-with-tooltip',"data-original-title" => t("messages.tooltips.save"),"data-placement" => "bottom"
            = link_to t("buttons.cancel"), {:action => 'index'}

app/views/ous/_list.html.haml
-if @ous.count > 20
  .apple_pagination
    = will_paginate @ous

%table.table.table-striped
  %thead
    -if current_user.admin?
      %th= t("ous.id")
    %th= t("ous.code")
    %th= t("ous.full_name")
    %th= t("ous.ate_name")
    %th= t("ous.mouo_name")
    %th= t("ous.contact_fio")
    %th= t("ous.contact_phone")
    -if current_user.admin?
      %th= t("ous.created_at")
      %th= t("ous.updated_at")
    %th= t("ous.actions.title")
  %tbody
    - @ous.each do |row|
      %tr
        -if current_user.admin?
          %td= row.id.to_s
        %td= row.code.to_s
        %td= row.name.to_s
        %td= row.ate.name.to_s
        %td= row.mouo.name.to_s
        %td= row.contact_fio.to_s
        %td= row.contact_phone.to_s
        -if current_user.admin?
          %td= row.created_at.to_s
          %td= row.updated_at.to_s
        %td
          - if can? :edit, row
            = link_to edit_ou_path(row) do
              = bootstrap_icon "pencil", width: 15, height: 15, fill: "green"
          - if can? :destroy, row
            = link_to ou_path(row), :method => :delete,  data: { confirm: t('delete_confirm')} do
              = bootstrap_icon "trash", width: 15, height: 15, fill: "red"

-if @ous.count > 20
  .apple_pagination
    = will_paginate @ous

app/views/ous/edit.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/ous/index.html.haml
.row
  .span9
    %h3.pull-left= t("ous.list.title")
    -# = render_notice
    %span.top-panel-actions
      %table.table.borderless
        %tr
          %td
            = form_tag ous_path, :method => 'get', :id => "ous_search" do
              %p
                = text_field_tag :search, params[:search]
                = button_tag(type: "submit", class: "btn btn-default", :name => nil) do
                  = bootstrap_icon "search", width: 25, height: 25, fill: "blue"
          %td
            -if can? :create, Ou
              = link_to new_ou_path do
                = bootstrap_icon "file-plus", width: 15, height: 15, fill: "blue"
            = link_to ous_export_path do
              = bootstrap_icon "download", width: 15, height: 15, fill: "blue"
            -if can? :import, Ou
              = link_to new_ous_import_path do
                = bootstrap_icon "upload", width: 15, height: 15, fill: "blue"


    %span.marks-filter-target
      = render :partial => 'list', :locals => {:legend => t(".title")}

app/views/ous/new.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/ous/show.html.haml
-# -@id=params[:id]
%h1 Наименование проекта
%h2=@ou.name.to_s
%table
  %tr
    %td=t("ous.code")
    %td=@ou.code.to_s
  %tr
    %td=t("ous.full_name")
    %td=@ou.name
%div
  = link_to "Вернуться", ous_path, :class => "btn btn-primary btn-mini"