config/routes.rb
require 'sidekiq/web'
# root 'pages#home'
# skip_before_action :authenticate_user!, :only => [:index]

Rails.application.routes.draw do
  # devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  get '/ates/export', to: 'ates#export'
  resources :ates
  resources :ates_imports, only: [:new, :create]

  get '/objectivity_ate_marks/export', to: 'objectivity_ate_marks#export'
  resources :objectivity_ate_marks
  resources :objectivity_ate_marks_imports, only: [:new, :create]

  get '/objectivity_ou_marks/export', to: 'objectivity_ou_marks#export'
  resources :objectivity_ou_marks
  resources :objectivity_ou_marks_imports, only: [:new, :create]


  get '/monitoring_objectivity_ous/export', to: 'monitoring_objectivity_ous#export'
  resources :monitoring_objectivity_ous
  resources :monitoring_objectivity_ous_imports, only: [:new, :create]

  get '/monitoring_objectivity_ates/export', to: 'monitoring_objectivity_ates#export'
  resources :monitoring_objectivity_ates
  resources :monitoring_objectivity_ates_imports, only: [:new, :create]

  get '/mouos/export', to: 'mouos#export'
  resources :mouos
  resources :mouos_imports, only: [:new, :create]

  get '/ous/export', to: 'ous#export'
  resources :ous
  resources :ous_imports, only: [:new, :create]

  get '/archive2021_ous/export', to: 'archive2021_ous#export'
  resources :archive2021_ous

  get '/archive2021_ates/export', to: 'archive2021_ates#export'
  resources :archive2021_ates

  get '/archive2021_ou_marks/export', to: 'archive2021_ou_marks#export'
  resources :archive2021_ou_marks

  get '/archive2021_ate_marks/export', to: 'archive2021_ate_marks#export'
  resources :archive2021_ate_marks

  get '/recreate_logins_for_all_users', to: 'home#recreate_logins_for_all_users'
  get '/help', to: 'home#help'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/monitoring_objectivity_ates_imports', to: 'monitoring_objectivity_ates_imports#new'
  get '/monitoring_objectivity_ous_imports', to: 'monitoring_objectivity_ous_imports#new'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  # root :to => redirect("/users/sign_in")

  root :to => 'home#index'

  #
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.haml
%footer.footer.text-muted.bg-light
  .container
    %span
      © #{Date.today.year} РЦОИ и ОКО
    %ul.list-inline.mb-0.float-right
      %li.list-inline-item.mr-3= link_to t("navigation.help"), help_path
      %li.list-inline-item.mr-3= link_to t("navigation.privacy"), privacy_path

app/views/shared/_head.html.haml
-#%title= Rails.configuration.application_name
%title= "Мониторинг"
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/shared/_navbar.html.haml
- if user_masquerade?
  .alert.alert-warning.text-center
    You're logged in as
    %b
      = current_user.name
      (#{current_user.email})
    = link_to back_masquerade_path(current_user) do
      = icon("fas", "times")
      Logout
%nav.navbar.navbar-expand-md.navbar-light.bg-light
  .container
    = link_to "Мониторинг", root_path, class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarsExample04", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarMain", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarMain.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto.mt-2.mt-md-0
      %ul.navbar-nav
        %li.nav-item= link_to t("navigation.announcements"), announcements_path, class: "nav-link #{unread_announcements(current_user)}"
        - if user_signed_in?
          -#%li.nav-item
          -#  = link_to notifications_path, class: "nav-link" do
          -#    %span
          -#      %i.far.fa-bell{"aria-hidden" => "true"}
          %li.nav-item.dropdown
            = link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do
              = bootstrap_icon "graph-up", width: 15, height: 15, fill: "green"
            #nav-account-dropdown.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbar-dropdown"}
              - if current_user.admin? or current_user.mouo_role? or current_user.ous_role?
                = link_to t("navigation.monitoring_objectivity_ous"), monitoring_objectivity_ous_path, class: "dropdown-item"
              - if current_user.admin? or current_user.mouo_role?
                = link_to t("navigation.monitoring_objectivity_ates"), monitoring_objectivity_ates_path, class: "dropdown-item"
              - if current_user.admin? or current_user.expert_role?
                = link_to t("navigation.objectivity_ate_marks"), objectivity_ate_marks_path, class: "dropdown-item"
              - if current_user.admin? or current_user.expert_role?
                = link_to t("navigation.objectivity_ou_marks"), objectivity_ou_marks_path, class: "dropdown-item"
          %li.nav-item.dropdown
            = link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do
              = bootstrap_icon "collection", width: 15, height: 15, fill: "green"
            #nav-account-dropdown.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbar-dropdown"}
              - if current_user.admin? or current_user.mouo_role? or current_user.ous_role?
                = link_to t("navigation.archive2021_ous"), archive2021_ous_path, class: "dropdown-item"
              - if current_user.admin? or current_user.mouo_role?
                = link_to t("navigation.archive2021_ates"), archive2021_ates_path, class: "dropdown-item"
              - if current_user.admin? or current_user.expert_role?
                = link_to t("navigation.archive2021_ate_marks"), archive2021_ate_marks_path, class: "dropdown-item"
              - if current_user.admin? or current_user.expert_role?
                = link_to t("navigation.archive2021_ou_marks"), archive2021_ou_marks_path, class: "dropdown-item"
          %li.nav-item.dropdown
            = link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do
              = bootstrap_icon "tools", width: 15, height: 15, fill: "green"
            #nav-account-dropdown.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbar-dropdown"}
              = link_to t("navigation.ates"), ates_path, class: "dropdown-item"
              = link_to t("navigation.mouos"), mouos_path, class: "dropdown-item"
              = link_to t("navigation.ous"), ous_path, class: "dropdown-item"
          %li.nav-item.dropdown
            = link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do
              -if !avatar_path(current_user).nil?
                = image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded"
              -else
                = bootstrap_icon "user", width: 15, height: 15, fill: "blue"
            #nav-account-dropdown.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbar-dropdown"}
              - if current_user.admin? && respond_to?(:admin_root_path)
                = link_to t("navigation.admin_area"), admin_root_path, class: "dropdown-item"
              = link_to t("navigation.settings"), edit_user_registration_path, class: "dropdown-item"
              .dropdown-divider
              = link_to t("navigation.logout"), destroy_user_session_path, method: :delete, class: "dropdown-item"
        - else
          -#%li.nav-item= link_to t("navigation.signup"), new_user_registration_path, class: "nav-link"
          %li.nav-item= link_to t("navigation.login"), new_user_session_path, class: "nav-link"

app/views/shared/_notices.html.haml
%body
  .lead
    - flash.each do |msg_type, message|
      %div{:class => "alert #{bootstrap_class_for(msg_type)}"}
        .container
          %button.close{"data-dismiss" => "alert"}
            %span ×
          = message