config/routes.rb
require 'sidekiq/web'
# root 'pages#home'
# skip_before_action :authenticate_user!, :only => [:index]

Rails.application.routes.draw do
  # devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  get '/ates/export', to: 'ates#export'
  resources :ates
  resources :ates_imports, only: [:new, :create]

  get '/objectivity_ate_marks/export', to: 'objectivity_ate_marks#export'
  resources :objectivity_ate_marks
  resources :objectivity_ate_marks_imports, only: [:new, :create]

  get '/objectivity_ou_marks/export', to: 'objectivity_ou_marks#export'
  resources :objectivity_ou_marks
  resources :objectivity_ou_marks_imports, only: [:new, :create]


  get '/monitoring_objectivity_ous/export', to: 'monitoring_objectivity_ous#export'
  resources :monitoring_objectivity_ous
  resources :monitoring_objectivity_ous_imports, only: [:new, :create]

  get '/monitoring_objectivity_ates/export', to: 'monitoring_objectivity_ates#export'
  resources :monitoring_objectivity_ates
  resources :monitoring_objectivity_ates_imports, only: [:new, :create]

  get '/mouos/export', to: 'mouos#export'
  resources :mouos
  resources :mouos_imports, only: [:new, :create]

  get '/ous/export', to: 'ous#export'
  resources :ous
  resources :ous_imports, only: [:new, :create]

  get '/archive2021_ous/export', to: 'archive2021_ous#export'
  resources :archive2021_ous

  get '/archive2021_ates/export', to: 'archive2021_ates#export'
  resources :archive2021_ates

  get '/archive2021_ou_marks/export', to: 'archive2021_ou_marks#export'
  resources :archive2021_ou_marks

  get '/archive2021_ate_marks/export', to: 'archive2021_ate_marks#export'
  resources :archive2021_ate_marks

  get '/recreate_logins_for_all_users', to: 'home#recreate_logins_for_all_users'
  get '/help', to: 'home#help'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/monitoring_objectivity_ates_imports', to: 'monitoring_objectivity_ates_imports#new'
  get '/monitoring_objectivity_ous_imports', to: 'monitoring_objectivity_ous_imports#new'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  # root :to => redirect("/users/sign_in")

  root :to => 'home#index'

  #
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/objectivity_ate_mark.rb
class ObjectivityAteMark < ApplicationRecord

  include PgSearch::Model

  belongs_to :monitoring_objectivity_ate
  belongs_to :user
  validates :monitoring_objectivity_ate_id, presence: true
  validates :user_id, presence: true
  validates :mark01, presence: true
  validates :mark02, presence: true
  validates :mark03, presence: true
  validates :mark04, presence: true
  validates :mark05, presence: true
  validates :mark06, presence: true
  validates :mark07, presence: true
  validates :mark08, presence: true
  validates :mark09, presence: true
  validates :mark10, presence: true
  validates :mark11, presence: true
  validates :mark12, presence: true
  validates :mark13, presence: true
  validates :mark14, presence: true
  validates :mark15, presence: true
  validates :mark16, presence: true
  validates :mark17, presence: true
  validates :mark18, presence: true
  validates :mark19, presence: true
  validates :mark20, presence: true
  validates :mark21, presence: true
  validates :mark22, presence: true
  validates :mark23, presence: true
  validates :mark24, presence: true
  validates :mark25, presence: true
  validates :mark26, presence: true
  validates :mark27, presence: true
  validates :mark28, presence: true
  validates :mark29, presence: true
  validates :mark30, presence: true
  validates :mark31, presence: true
  validates :mark32, presence: true
  validates :mark33, presence: true
  validates :mark34, presence: true
  validates :mark35, presence: true
  validates :mark36, presence: true
  validates :mark37, presence: true
  validates :mark38, presence: true
  validates :mark39, presence: true
  validates :mark40, presence: true
  validates :mark41, presence: true

  def self.search(search)
    if search.length > 0
      self.joins("join monitoring_objectivity_ates mon ON mon.id = objectivity_ate_marks.monitoring_objectivity_ate_id join mouos m ON m.id = mon.mouo_id ").where(" (cast(m.code as varchar(6)) || m.name) LIKE ?", "%#{search}%")
      # where('code || cast(code as varchar(6)) LIKE ?', "%#{search}%")
    else
      self.where("1 = 1")
    end
  end


  def self.filtr(filter)
    if filter.length > 0
      filter = filter.to_i
      self.where(" status = #{filter}")
    else
      self.where("1 = 1")
    end
  end

  def marksum
    begin
      return (self.mark01 + self.mark02 + self.mark03 + self.mark04 + self.mark05 + self.mark06 + self.mark07 + self.mark08 + self.mark09 + self.mark10 +
        self.mark11 + self.mark12 + self.mark13 + self.mark14 + self.mark15 + self.mark16 + self.mark17 + self.mark18 + self.mark19 + self.mark20 +
        self.mark21 + self.mark22 + self.mark23 + self.mark24 + self.mark25 + self.mark26 + self.mark27 + self.mark28 + self.mark29 + self.mark30 +
        self.mark31 + self.mark32 + self.mark33 + self.mark34 + self.mark35 + self.mark36 + self.mark37 + self.mark38 + self.mark39 + self.mark40 +
        self.mark41)
    rescue
      return("Не заполнено")
    end
  end

  self.per_page = 20

  has_rich_text :notes

  def formatted_body
    innertext = Richtext::CodeBlocks::HtmlService.render(self.notes.to_s).html_safe
    # rescue innertext = Richtext::CodeBlocks::HtmlService.latex(innertext).html_safe
    innertext
  end

  # set per_page globally
  WillPaginate.per_page = 20

end

app/controllers/objectivity_ate_marks_controller.rb
class ObjectivityAteMarksController < ApplicationController
  load_and_authorize_resource :instance_name => :item
  before_action :authenticate_user!

  def index
    @statuses = [{"name"=>"В работе", "id"=> 0}, {"name"=>"Завершена", "id"=>1}]
    @objectivity_ate_marks = ObjectivityAteMark.accessible_by(current_ability).paginate(page: params[:page]).order('id ASC')
    if current_user.admin?
      if !params[:search].nil?
        @objectivity_ate_marks = ObjectivityAteMark.accessible_by(current_ability).search(params[:search]).paginate(page: params[:page]).order('id ASC')
      end
      if !params[:filter].nil?
        @objectivity_ate_marks = ObjectivityAteMark.accessible_by(current_ability).filtr(params[:filter]).paginate(page: params[:page]).order('id ASC')
      end
    else
      if !params[:search].nil?
        @objectivity_ate_marks = ObjectivityAteMark.accessible_by(current_ability).search(params[:search]).paginate(page: params[:page]).order('id ASC')
      end
      if !params[:filter].nil?
        @objectivity_ate_marks = ObjectivityAteMark.accessible_by(current_ability).filtr(params[:filter]).paginate(page: params[:page]).order('id ASC')
      end
      if !params[:search].nil? and !params[:filter].nil?
        @objectivity_ate_marks = ObjectivityAteMark.accessible_by(current_ability).filtr(params[:filter]).search(params[:search]).paginate(page: params[:page]).order('id ASC')
      end
    end
  end

  def export
    @objectivity_ate_marks = ObjectivityAteMark.accessible_by(current_ability)
    render xlsx: 'ous_list_' + DateTime.now.getlocal.to_s.gsub(' ', '-').gsub(':', '.'), template: '/objectivity_ate_marks/export.xlsx.axlsx'
  end

  def new
    @statuses = [{"name"=>"В работе", "id"=> 0}, {"name"=>"Завершена", "id"=>1}]
    @monitoring_objectivity_ates = MonitoringObjectivityAte.accessible_by(current_ability).where (" id not in (select monitoring_objectivity_ate_id from objectivity_ate_marks) ")
    @objectivity_ate_mark_not_ended = ObjectivityAteMark.accessible_by(current_ability).where(:user_id => current_user.id).where(:status => 0)
    if @objectivity_ate_mark_not_ended.count > 0
      @objectivity_ate_mark = @objectivity_ate_mark_not_ended.first
      @monitoring_objectivity_ate = MonitoringObjectivityAte.find(@objectivity_ate_mark.monitoring_objectivity_ate.id)
      flash[:success] = t("objectivity_ate_marks.errors.cant_create_new_privous_was")
      render :edit
    else
      if @monitoring_objectivity_ates.count > 0
        @monitoring_objectivity_ate = @monitoring_objectivity_ates[rand(@monitoring_objectivity_ates.count).to_i]
        @objectivity_ate_mark = ObjectivityAteMark.new
        @objectivity_ate_mark.monitoring_objectivity_ate_id = @monitoring_objectivity_ate.id
        @objectivity_ate_mark.user_id = current_user.id
        @objectivity_ate_mark.mark01 = 0
        @objectivity_ate_mark.mark02 = 0
        @objectivity_ate_mark.mark03 = 0
        @objectivity_ate_mark.mark04 = 0
        @objectivity_ate_mark.mark05 = 0
        @objectivity_ate_mark.mark06 = 0
        @objectivity_ate_mark.mark07 = 0
        @objectivity_ate_mark.mark08 = 0
        @objectivity_ate_mark.mark09 = 0
        @objectivity_ate_mark.mark10 = 0
        @objectivity_ate_mark.mark11 = 0
        @objectivity_ate_mark.mark12 = 0
        @objectivity_ate_mark.mark13 = 0
        @objectivity_ate_mark.mark14 = 0
        @objectivity_ate_mark.mark15 = 0
        @objectivity_ate_mark.mark16 = 0
        @objectivity_ate_mark.mark17 = 0
        @objectivity_ate_mark.mark18 = 0
        @objectivity_ate_mark.mark19 = 0
        @objectivity_ate_mark.mark20 = 0
        @objectivity_ate_mark.mark21 = 0
        @objectivity_ate_mark.mark22 = 0
        @objectivity_ate_mark.mark23 = 0
        @objectivity_ate_mark.mark24 = 0
        @objectivity_ate_mark.mark25 = 0
        @objectivity_ate_mark.mark26 = 0
        @objectivity_ate_mark.mark27 = 0
        @objectivity_ate_mark.mark28 = 0
        @objectivity_ate_mark.mark29 = 0
        @objectivity_ate_mark.mark30 = 0
        @objectivity_ate_mark.mark31 = 0
        @objectivity_ate_mark.mark32 = 0
        @objectivity_ate_mark.mark33 = 0
        @objectivity_ate_mark.mark34 = 0
        @objectivity_ate_mark.mark35 = 0
        @objectivity_ate_mark.mark36 = 0
        @objectivity_ate_mark.mark37 = 0
        @objectivity_ate_mark.mark38 = 0
        @objectivity_ate_mark.mark39 = 0
        @objectivity_ate_mark.mark40 = 0
        @objectivity_ate_mark.mark41 = 0
        @objectivity_ate_mark.status = 0
        if @monitoring_objectivity_ate.url01.present? or @monitoring_objectivity_ate.document01.present?
          @objectivity_ate_mark.mark01 = 1
        end
        if @monitoring_objectivity_ate.url02.present? or @monitoring_objectivity_ate.document02.present?
          @objectivity_ate_mark.mark02 = 1
        end
        if @monitoring_objectivity_ate.url03.present? or @monitoring_objectivity_ate.document03.present?
          @objectivity_ate_mark.mark03 = 1
        end
        if @monitoring_objectivity_ate.url04.present? or @monitoring_objectivity_ate.document04.present?
          @objectivity_ate_mark.mark04 = 1
        end
        if @monitoring_objectivity_ate.url05.present? or @monitoring_objectivity_ate.document05.present?
          @objectivity_ate_mark.mark05 = 1
        end
        if @monitoring_objectivity_ate.url06.present? or @monitoring_objectivity_ate.document06.present?
          @objectivity_ate_mark.mark06 = 1
        end
        if @monitoring_objectivity_ate.url07.present? or @monitoring_objectivity_ate.document07.present?
          @objectivity_ate_mark.mark07 = 1
        end
        if @monitoring_objectivity_ate.url08.present? or @monitoring_objectivity_ate.document08.present?
          @objectivity_ate_mark.mark08 = 1
        end
        if @monitoring_objectivity_ate.url09.present? or @monitoring_objectivity_ate.document09.present?
          @objectivity_ate_mark.mark09 = 1
        end
        if @monitoring_objectivity_ate.url10.present? or @monitoring_objectivity_ate.document10.present?
          @objectivity_ate_mark.mark10 = 1
        end
        if @monitoring_objectivity_ate.url11.present? or @monitoring_objectivity_ate.document11.present?
          @objectivity_ate_mark.mark11 = 1
        end
        sleep rand(2)
        @objectivity_ate_mark2 = ObjectivityAteMark.where(:monitoring_objectivity_ate_id => @monitoring_objectivity_ate.id)
        if !@objectivity_ate_mark.nil? and @objectivity_ate_mark2.count == 0
          @objectivity_ate_mark.monitoring_objectivity_ate = @monitoring_objectivity_ate
          @objectivity_ate_mark.save
          render :edit
        else
          flash[:success] = t("objectivity_ate_marks.errors.cant_create_new")
          redirect_to :action => 'index'
        end
      else
        flash[:success] = t("objectivity_ate_marks.errors.no_new")
        redirect_to :action => 'index'
      end
    end
  end

  def show
    @statuses = [{"name"=>"В работе", "id"=> 0}, {"name"=>"Завершена", "id"=>1}]
    @objectivity_ate_mark = ObjectivityAteMark.accessible_by(current_ability).find(params[:id])
  end

  def create
    @statuses = [{"name"=>"В работе", "id"=> 0}, {"name"=>"Завершена", "id"=>1}]
    @ates = Ate.accessible_by(current_ability)
    @mouos = Mouo.accessible_by(current_ability)
    @objectivity_ate_mark = ObjectivityAteMark.new(objectivity_ate_mark_params)
    if @objectivity_ate_mark.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @ates = Ate.all
    @statuses = [{"name"=>"В работе", "id"=> 0}, {"name"=>"Завершена", "id"=>1}]
    @objectivity_ate_mark = ObjectivityAteMark.find(params[:id])
    @monitoring_objectivity_ate = MonitoringObjectivityAte.find(@objectivity_ate_mark.monitoring_objectivity_ate.id)
  end

  def delete
    ObjectivityAteMark.accessible_by(current_ability).find(params[:id]).destroy
    return
  end

  def destroy
    @objectivity_ate_mark = ObjectivityAteMark.accessible_by(current_ability).find(params[:id])
    @objectivity_ate_mark.destroy
    respond_to do |format|
      format.html { redirect_to ous_url, notice: t("objectivity_ate_marks.notice.destroyed") }
      format.json { head :no_content }
    end
    # redirect :action => 'index'
  end

  def update
    @objectivity_ate_mark = ObjectivityAteMark.accessible_by(current_ability).find params[:id]
    # respond_to do |format|
    if @objectivity_ate_mark.update objectivity_ate_mark_params
      flash[:success] = t("objectivity_ate_marks.notice.updated")
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end


  def objectivity_ate_mark_params
    params.require(:objectivity_ate_mark).permit(:id, :monitoring_objectivity_ate_id, :user_id, :status,
        :mark01, :mark02, :mark03, :mark04, :mark05, :mark06, :mark07, :mark08, :mark09, :mark10,
        :mark11, :mark12, :mark13, :mark14, :mark15, :mark16, :mark17, :mark18, :mark19, :mark20,
        :mark21, :mark22, :mark23, :mark24, :mark25, :mark26, :mark27, :mark28, :mark29, :mark30,
        :mark31, :mark32, :mark33, :mark34, :mark35, :mark36, :mark37, :mark38, :mark39, :mark40,
        :mark41, :notes)
  end

end

app/views/objectivity_ate_marks/_filter_fields.html.haml
-# = text_field_tag "filter[ou_id]", filter[:ou_id], :placeholder => t("helpers.placeholder.ou_id"), "data-autosubmit" => "keyup"

- heavy_filter = heavy_filter || false
- unless heavy_filter
- else
  = link_to "#", :class => "filter-btn btn" do
    %i.icon-
    %span= t("buttons.search")

app/views/objectivity_ate_marks/_list.html.haml
-if @objectivity_ate_marks.count > 20
  .apple_pagination
    = will_paginate @objectivity_ate_marks

%table.table.table-striped
  %thead
    -if current_user.admin?
      %th= t("ous.id")
    %th= t("objectivity_ate_marks.mouo")
    -if current_user.admin?
      %th= t("objectivity_ate_marks.user")
    %th= t("objectivity_ate_marks.marks")
    %th= t("objectivity_ate_marks.sum_marks")
    %th= t("objectivity_ate_marks.status")
    -if current_user.admin?
      %th= t("objectivity_ate_marks.created_at")
      %th= t("objectivity_ate_marks.updated_at")
    %th= t("ous.actions.title")
  %tbody
    - @objectivity_ate_marks.each do |row|
      %tr
        -if current_user.admin?
          %td= row.id.to_s
          %td= row.user.first_name
        %td= row.monitoring_objectivity_ate.mouo.name
        %td
          =row.mark01
          =row.mark02
          =row.mark03
          =row.mark04
          =row.mark05
          =row.mark06
          =row.mark07
          =row.mark08
          =row.mark09
          =row.mark10
          =row.mark11
          =row.mark12
          =row.mark13
          =row.mark14
          =row.mark15
          =row.mark16
          =row.mark17
          =row.mark18
          =row.mark19
          =row.mark20
          =row.mark21
          =row.mark22
          =row.mark23
          =row.mark24
          =row.mark25
          =row.mark26
          =row.mark27
          =row.mark28
          =row.mark29
          =row.mark30
          =row.mark31
          =row.mark32
          =row.mark33
          =row.mark34
          =row.mark35
          =row.mark36
          =row.mark37
          =row.mark38
          =row.mark39
          =row.mark40
          =row.mark41
        %td
          =row.marksum
        %td
          -if row.status == 1
            ="Завершена"
          -else
            ="В работе"
        -if current_user.admin?
          %td= row.created_at.strftime("%d.%m.%Y\u00a0%H:%M")
          %td= row.updated_at.strftime("%d.%m.%Y\u00a0%H:%M")
        %td
          - if can? :edit, row
            = link_to edit_objectivity_ate_mark_path(row) do
              = bootstrap_icon "pencil", width: 15, height: 15, fill: "green"
          - if can? :destroy, row
            = link_to objectivity_ate_mark_path(row), :method => :delete,  data: { confirm: t('delete_confirm')} do
              = bootstrap_icon "trash", width: 15, height: 15, fill: "red"
          =""

-if @objectivity_ate_marks.count > 20
  .apple_pagination
    = will_paginate @objectivity_ate_marks

app/views/objectivity_ate_marks/_new.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/objectivity_ate_marks/edit.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/objectivity_ate_marks/index.html.haml
.row
  .span9
    %span.top-panel-actions
      %table.table.borderless
        %tr
          %td
            %h3.pull-left= t("objectivity_ate_marks.list.title")
          %td{:width=>100}
            = link_to new_objectivity_ate_mark_path do
              = bootstrap_icon "file-plus", width: 15, height: 15, fill: "blue"
            -# = link_to objectivity_ate_marks_export_path do
            -#   = bootstrap_icon "download", width: 15, height: 15, fill: "blue"
            -# = link_to new_objectivity_ate_marks_import_path do
            -#   = bootstrap_icon "upload", width: 15, height: 15, fill: "blue"

    = form_tag objectivity_ate_marks_path,:method => "GET", :class => "simple-filter objectivity_ate_marks-filter", "data-button" => "a#objectivity_ate_marks-search", "data-target" => ".objectivity_ate_marks-filter-target" do
      = render :partial => "filter_fields",:locals => {:filter => @filter}

    = form_tag objectivity_ate_marks_path, :method => 'get', :id => "objectivity_ate_marks_search" do
      %p
        = t("objectivity_ate_marks.filter.code_or_name")
        = text_field_tag "search", params[:search]
        = t("objectivity_ate_marks.filter.status")
        = select_tag "filter", options_for_select(@statuses.collect {|p| [ p['name'], p['id'] ] }, :selected => params[:filter]),
            {:include_blank => true, :class => "simple-chosen", "data-placeholder" => t("helpers.placeholder.statuses") ,"data-autosubmit" => "change"}
        = button_tag(type: "submit", class: "btn btn-default", :name => nil) do
          = bootstrap_icon "search", width: 25, height: 25, fill: "blue"


    -# - md = []
    -# - @objectivity_ate_marks.each do |row|
    -#   - i = 0
    -#   - while i < 16
    -#     - i = i + 1
    -#     -if row.entered_number(i)
    -#       - md[i] = (md[i] || 0) + 1
    -# - i = 0
    -# - mdata = Array.new
    -# - while i < 16
    -#   - i = i + 1
    -#   - b = ["п.#{i}", md[i]]
    -#   - mdata.append(b)
    -# -# = mdata
    -# = column_chart mdata, stacked: true, download: {filename: "objectivity_ate_marks_" + DateTime.now.getlocal.to_s.gsub(' ', '-').gsub(':', '.')}


    %span.marks-filter-target
      = render :partial => 'list', :locals => {:legend => t("objectivity_ate_marks.title")}

app/views/objectivity_ate_marks/new.html.haml
= render :partial => 'new', :locals => {:legend => t(".title")}

app/views/objectivity_ate_marks/show.html.haml
-#-# -@id=params[:id]
-#%h1 Наименование проекта
-#%h2=@ou.name.to_s
-#%table
-#  %tr
-#    %td=t("ous.code")
-#    %td=@ou.code.to_s
-#  %tr
-#    %td=t("ous.full_name")
-#    %td=@ou.name
-#%div
-#  = link_to "Вернуться", ous_path, :class => "btn btn-primary btn-mini"